// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "aiEnabled": boolean;
      "aiBaseURL": string;
      "aiModel": string;
      "aiReasoningEffort": string;
    };
  }
}
