export type CCFLevel = "A" | "B" | "C";

// Generated from 第七版中国计算机学会推荐国际学术会议和期刊目录（正式版）.pdf
export const CCF_CATALOG: Record<CCFLevel, string[]> = {
  A: [
    "AAAI",
    "AAAI AAAI Conference on Artificial Intelligence",
    "AAAI Conference on Artificial Intelligence",
    "ACL",
    "ACL Annual Meeting of the Association for Computational Linguistics ACL",
    "ACM",
    "ACM Conference on Computer and Communications Security",
    "ACM Conference On Computer-Supported Cooperative Work And Social Computing",
    "ACM Conference on Human Factors in Computing Systems",
    "ACM International Conference on Applications, Technologies, Architectures, and Protocols for Computer Communication",
    "ACM International Conference on Mobile Computing and Networking",
    "ACM International Conference on the Foundations of Software Engineering",
    "ACM international joint conference on Pervasive and Ubiquitous Computing",
    "ACM MM ACM International Conference on Multimedia",
    "ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
    "ACM SIGMOD Conference",
    "ACM SIGOPS ATC 10 EuroSys European Conference on Computer Systems",
    "ACM SIGPLAN Conference on Programming Language Design and Implementation",
    "ACM SIGPLAN Symposium on Principles & Practice of Parallel Programming",
    "ACM SIGPLAN-SIGACT Symposium on Principles of Programming Languages",
    "ACM Special Interest Group on Computer Graphics",
    "ACM Symposium on Operating Systems Principles",
    "ACM Symposium on the Theory of Computing",
    "ACM Symposium on User Interface Software and Technology",
    "ACM Transactions on Architecture and Code Optimization",
    "ACM Transactions on Computer Systems",
    "ACM Transactions on Computer-Human Interaction",
    "ACM Transactions on Graphics",
    "ACM Transactions on Information Systems",
    "ACM Transactions on Programming Languages and Systems",
    "ACM Transactions on Software Engineering and Methodology",
    "ACM Transactions on Storage",
    "ACM-SIAM Symposium on Discrete Algorithms",
    "ACM/IEEE Symposium on Logic in Computer Science",
    "AI",
    "AI Artificial Intelligence",
    "Annual Meeting of the Association for Computational Linguistics ACL",
    "Artificial Intelligence",
    "ASE",
    "ASE International Conference on Automated Software Engineering IEEE/",
    "ASPLOS",
    "ASPLOS International Conference on Architectural Support for Programming Languages and Operating Systems",
    "Bioinformatics",
    "Bioinformatics Bioinformatics",
    "CAV",
    "CAV International Conference on Computer Aided Verification",
    "CCS",
    "CCS ACM Conference on Computer and Communications Security",
    "CHI",
    "CHI ACM Conference on Human Factors in Computing Systems",
    "Conference on Neural Information Processing Systems",
    "Conference on Object-Oriented Programming Systems, Languages, and Applications",
    "CRYPTO",
    "CRYPTO International Cryptology Conference",
    "CSCW",
    "CSCW ACM Conference On Computer-Supported Cooperative Work And Social Computing",
    "CVPR",
    "CVPR IEEE/CVF Computer Vision and Pattern Recognition Conference",
    "DAC",
    "DAC Design Automation Conference",
    "Design Automation Conference",
    "EUROCRYPT",
    "EUROCRYPT International Conference on the Theory and Applications of Cryptographic Techniques",
    "FAST",
    "FAST USENIX Conference on File and Storage Technologies",
    "FM",
    "FM International Symposium on Formal Methods FME",
    "FOCS",
    "FOCS IEEE Annual Symposium on Foundations of Computer Science",
    "FSE",
    "FSE ACM International Conference on the Foundations of Software Engineering",
    "HPCA",
    "HPCA IEEE International Symposium on High Performance Computer Architecture",
    "HPDC",
    "HPDC The International ACM Symposium on High-Performance Parallel and Distributed Computing",
    "IANDC",
    "IANDC Information and Computation",
    "ICCV",
    "ICCV International Conference on Computer Vision",
    "ICDE",
    "ICDE IEEE International Conference on Data Engineering",
    "ICLR",
    "ICLR International Conference on Learning Representations OpenReview",
    "ICML",
    "ICML International Conference on Machine Learning",
    "ICSE",
    "ICSE International Conference on Software Engineering IEEE/",
    "IEEE Annual Symposium on Foundations of Computer Science",
    "IEEE International Conference on Computer Communications",
    "IEEE International Conference on Data Engineering",
    "IEEE International Symposium on High Performance Computer Architecture",
    "IEEE Proceedings of the IEEE",
    "IEEE Symposium on Security and Privacy",
    "IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems",
    "IEEE Transactions on Computers",
    "IEEE Transactions on Dependable and Secure Computing",
    "IEEE Transactions on Image Processing",
    "IEEE Transactions on Information Forensics and Security",
    "IEEE Transactions on Information Theory",
    "IEEE Transactions on Knowledge and Data Engineering",
    "IEEE Transactions on Mobile Computing",
    "IEEE Transactions on Multimedia",
    "IEEE Transactions on Parallel and Distributed Systems",
    "IEEE Transactions on Pattern Analysis and Machine Intelligence",
    "IEEE Transactions on Services Computing",
    "IEEE Transactions on Software Engineering",
    "IEEE Transactions on Visualization and Computer Graphics",
    "IEEE/ACM International Symposium on Microarchitecture IEEE/",
    "IEEE/CVF Computer Vision and Pattern Recognition Conference",
    "IJCV",
    "IJCV International Journal of Computer Vision",
    "IJHCS",
    "IJHCS International Journal of Human-Computer Studies",
    "INFOCOM",
    "INFOCOM IEEE International Conference on Computer Communications",
    "Information and Computation",
    "International ACM SIGIR Conference on Research and Development in Information Retrieval",
    "International Conference for High Performance Computing, Networking, Storage, and Analysis",
    "International Conference on Architectural Support for Programming Languages and Operating Systems",
    "International Conference on Automated Software Engineering IEEE/",
    "International Conference on Computer Aided Verification",
    "International Conference on Computer Vision",
    "International Conference on Learning Representations OpenReview",
    "International Conference on Machine Learning",
    "International Conference on Software Engineering IEEE/",
    "International Conference on the Theory and Applications of Cryptographic Techniques",
    "International Conference on Very Large Data Bases Morgan Kaufmann/",
    "International Cryptology Conference",
    "International Journal of Computer Vision",
    "International Journal of Human-Computer Studies",
    "International Symposium on Computer Architecture IEEE/",
    "International Symposium on Formal Methods FME",
    "International Symposium on Software Testing and Analysis",
    "International World Wide Web Conference",
    "ISCA",
    "ISCA International Symposium on Computer Architecture IEEE/",
    "ISSTA",
    "ISSTA International Symposium on Software Testing and Analysis",
    "JACM",
    "JACM Journal of the ACM",
    "JMLR",
    "JMLR Journal of Machine Learning Research",
    "Journal",
    "Journal of Cryptology",
    "Journal of Machine Learning Research",
    "Journal of the ACM",
    "LICS",
    "LICS ACM/IEEE Symposium on Logic in Computer Science",
    "MICRO",
    "MICRO IEEE/ACM International Symposium on Microarchitecture IEEE/",
    "MM ACM International Conference on Multimedia",
    "MobiCom",
    "MobiCom ACM International Conference on Mobile Computing and Networking",
    "NDSS",
    "NDSS Network and Distributed System Security Symposium ISOC",
    "Network and Distributed System Security Symposium ISOC",
    "Neural Information Processing Systems",
    "NeurIPS",
    "NeurIPS Conference on Neural Information Processing Systems",
    "NIPS",
    "NSDI",
    "NSDI Symposium on Network System Design and Implementation",
    "of Cryptology",
    "OOPSLA",
    "OOPSLA Conference on Object-Oriented Programming Systems, Languages, and Applications",
    "OSDI",
    "OSDI USENIX Symposium on Operating Systems Design and Implementation",
    "PLDI",
    "PLDI ACM SIGPLAN Conference on Programming Language Design and Implementation",
    "POPL",
    "POPL ACM SIGPLAN-SIGACT Symposium on Principles of Programming Languages",
    "PPoPP",
    "PPoPP ACM SIGPLAN Symposium on Principles & Practice of Parallel Programming",
    "Proc.",
    "Proc. IEEE Proceedings of the IEEE",
    "S&P",
    "S&P IEEE Symposium on Security and Privacy",
    "SC",
    "SC International Conference for High Performance Computing, Networking, Storage, and Analysis",
    "Science China Information Sciences Science in China Press/Springer",
    "SCIS",
    "SCIS Science China Information Sciences Science in China Press/Springer",
    "Security USENIX Security Symposium USENIX Association",
    "SIAM Journal on Computing",
    "SICOMP",
    "SICOMP SIAM Journal on Computing",
    "SIGCOMM",
    "SIGCOMM ACM International Conference on Applications, Technologies, Architectures, and Protocols for Computer Communication",
    "SIGGRAPH",
    "SIGGRAPH ACM Special Interest Group on Computer Graphics",
    "SIGIR",
    "SIGIR International ACM SIGIR Conference on Research and Development in Information Retrieval",
    "SIGKDD",
    "SIGKDD ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
    "SIGMOD",
    "SIGMOD ACM SIGMOD Conference",
    "SIGOPS ATC 10 EuroSys European Conference on Computer Systems",
    "SODA",
    "SODA ACM-SIAM Symposium on Discrete Algorithms",
    "SOSP",
    "SOSP ACM Symposium on Operating Systems Principles",
    "STOC",
    "STOC ACM Symposium on the Theory of Computing",
    "Symposium on Network System Design and Implementation",
    "TACO",
    "TACO ACM Transactions on Architecture and Code Optimization",
    "TC",
    "TC IEEE Transactions on Computers",
    "TCAD",
    "TCAD IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems",
    "TDSC",
    "TDSC IEEE Transactions on Dependable and Secure Computing",
    "The International ACM Symposium on High-Performance Parallel and Distributed Computing",
    "The VLDB Journal",
    "The Web Conference",
    "The Web Conference 2 RTSS IEEE Real-Time Systems Symposium",
    "TIFS",
    "TIFS IEEE Transactions on Information Forensics and Security",
    "TIP",
    "TIP IEEE Transactions on Image Processing",
    "TIT",
    "TIT IEEE Transactions on Information Theory",
    "TKDE",
    "TKDE IEEE Transactions on Knowledge and Data Engineering",
    "TMC",
    "TMC IEEE Transactions on Mobile Computing",
    "TMM",
    "TMM IEEE Transactions on Multimedia",
    "TOCHI",
    "TOCHI ACM Transactions on Computer-Human Interaction",
    "TOCS",
    "TOCS ACM Transactions on Computer Systems",
    "TOG",
    "TOG ACM Transactions on Graphics",
    "TOIS",
    "TOIS ACM Transactions on Information Systems",
    "TOPLAS",
    "TOPLAS ACM Transactions on Programming Languages and Systems",
    "TOS",
    "TOS ACM Transactions on Storage",
    "TOSEM",
    "TOSEM ACM Transactions on Software Engineering and Methodology",
    "TPAMI",
    "TPAMI IEEE Transactions on Pattern Analysis and Machine Intelligence",
    "TPDS",
    "TPDS IEEE Transactions on Parallel and Distributed Systems",
    "TSC",
    "TSC IEEE Transactions on Services Computing",
    "TSE",
    "TSE IEEE Transactions on Software Engineering",
    "TVCG",
    "TVCG IEEE Transactions on Visualization and Computer Graphics",
    "UbiComp",
    "UbiComp ACM international joint conference on Pervasive and Ubiquitous Computing",
    "UIST",
    "UIST ACM Symposium on User Interface Software and Technology",
    "USENIX",
    "USENIX Conference on File and Storage Technologies",
    "USENIX Security USENIX Security Symposium USENIX Association",
    "USENIX Symposium on Operating Systems Design and Implementation",
    "VLDB",
    "VLDB International Conference on Very Large Data Bases Morgan Kaufmann/",
    "VLDBJ",
    "VLDBJ The VLDB Journal",
    "WWW",
    "WWW The Web Conference 2 RTSS IEEE Real-Time Systems Symposium",
  ],
  B: [
    "& Security",
    "AAMAS",
    "AAMAS Autonomous Agents and Multi-Agent Systems",
    "AAMAS International Joint Conference on Autonomous Agents and Multi-agent Systems",
    "ACM Conference on Embedded Networked Sensor Systems",
    "ACM International Conference on Emerging Networking Experiments and Technologies",
    "ACM International Conference on Information and Knowledge Management",
    "ACM International Conference on Intelligent User Interfaces",
    "ACM International Conference on Interactive Surfaces and Spaces",
    "ACM International Conference on Mobile Human- Computer Interaction",
    "ACM International Conference on Mobile Systems, Applications, and Services",
    "ACM International Conference on Supporting Group Work",
    "ACM International Conference on Web Search and Data Mining",
    "ACM Internet Measurement Conference ACM/",
    "ACM SIGGRAPH Symposium on Interactive 3D Graphics and Games",
    "ACM SIGGRAPH/Eurographics Symposium on Computer Animation",
    "ACM SIGMM International Conference on Multimedia Retrieval",
    "ACM SIGMOD-SIGACT-SIGAI Symposium on Principles of Database Systems",
    "ACM SIGPLAN International Conference on Function Programming",
    "ACM SIGPLAN/SIGBED International Conference on Languages, Compilers and Tools for Embedded Systems",
    "ACM Symposium on Cloud Computing",
    "ACM Symposium on Parallelism in Algorithms and Architectures",
    "ACM Symposium on Principles of Distributed Computing",
    "ACM Transactions on Algorithms",
    "ACM Transactions on Applied Perception",
    "ACM Transactions on Autonomous and Adaptive Systems",
    "ACM Transactions on Computational Logic",
    "ACM Transactions on Design Automation of Electronic Systems",
    "ACM Transactions on Embedded Computing Systems",
    "ACM Transactions on Internet Technology",
    "ACM Transactions on Knowledge Discovery from Data",
    "ACM Transactions on Mathematical Software",
    "ACM Transactions on Multimedia Computing, Communications and Applications",
    "ACM Transactions on Privacy and Security",
    "ACM Transactions on Reconfigurable Technology and Systems",
    "ACM Transactions on Sensor Networks",
    "ACM Transactions on the Web",
    "ACM/IEEE International Conference on Model Driven EngineeringLanguages and Systems IEEE/",
    "ACM/SIGDA International Symposium on Field-Programmable Gate Arrays",
    "ACSAC",
    "ACSAC Annual Computer Security Applications Conference",
    "Advanced Engineering Informatics",
    "AEI",
    "AEI Advanced Engineering Informatics",
    "Algorithmica",
    "Algorithmica Algorithmica",
    "Annual Computer Security Applications Conference",
    "Annual Conference of the European Association for Computer Graphics Wiley/ Blackwell",
    "Annual Conference on Computational Learning Theory",
    "Annual International Conference on Research in Computational Molecular Biology",
    "Annual International Conference on the Theory and Application of Cryptology and Information Security",
    "Annual Meeting of the Cognitive Science Society Psychology Press",
    "ASE",
    "ASE Automated Software Engineering",
    "ASIACRYPT",
    "ASIACRYPT Annual International Conference on the Theory and Application of Cryptology and Information Security",
    "Automated Software Engineering",
    "Autonomous Agents and Multi-Agent Systems",
    "BCRA",
    "BCRA Blockchain: Research and Applications 浙江大学出版社 /Elsevier",
    "BIBM",
    "BIBM IEEE International Conference on Bioinformatics and Biomedicine",
    "Blockchain: Research and Applications 浙江大学出版社 /Elsevier",
    "Briefings",
    "Briefings in Bioinformatics",
    "CADE",
    "CADE Conference on Automated Deduction",
    "CAiSE",
    "CAiSE International Conference on Advanced Information Systems Engineering",
    "CC",
    "CC Computational Complexity",
    "CC International Conference on Compiler Construction",
    "CCC",
    "CCC Conference on Computational Complexity",
    "CCF",
    "CCF TPCI CCF Transactions on Pervasive Computing and Interaction CCF/",
    "CGO",
    "CGO The International Symposium on Code Generation and Optimization IEEE/",
    "CHES",
    "CHES International Conference on Cryptographic Hardware and Embedded Systems",
    "CHIPS Hot Chips: A Symposium on High Performance Chips",
    "CIDR",
    "CIDR Conference on Innovative Data Systems Research Online Proceeding",
    "CIKM",
    "CIKM ACM International Conference on Information and Knowledge Management",
    "CLUSTER",
    "CLUSTER IEEE International Conference on Cluster Computing",
    "CN",
    "CN Computer Networks",
    "COCOON",
    "COCOON International Computing and Combinatorics Conference",
    "Cognition",
    "Cognition Cognition",
    "CogSci",
    "CogSci Annual Meeting of the Cognitive Science Society Psychology Press",
    "COLING",
    "COLING International Conference on Computational Linguistics International Committee on Computational Linguistics",
    "COLT",
    "COLT Annual Conference on Computational Learning Theory",
    "Computation",
    "Computational",
    "Computational Biology Public Library of Science",
    "Computational Complexity",
    "Computational Linguistics",
    "Computer Journal",
    "Computer Networks",
    "Computer Supported Cooperative Work",
    "Computer Vision and Image Understanding",
    "Computers",
    "Computers & Security",
    "Computing",
    "CONCUR",
    "CONCUR International Conference on Concurrency Theory",
    "CoNEXT",
    "CoNEXT ACM International Conference on Emerging Networking Experiments and Technologies",
    "Conference on Automated Deduction",
    "Conference on Computational Complexity",
    "Conference on Empirical Methods in Natural Language Processing ACL",
    "Conference on Innovative Data Systems Research Online Proceeding",
    "Conference on Uncertainty in Artificial Intelligence AUAI",
    "Conference on Web and Internet Economics",
    "CP",
    "CP International Conference on Principles and Practice of Constraint Programming",
    "CSCW",
    "CSCW Computer Supported Cooperative Work",
    "CSFW",
    "CSFW IEEE Computer Security Foundations Workshop",
    "CVIU",
    "CVIU Computer Vision and Image Understanding",
    "Cybersecurity",
    "Cybersecurity Cybersecurity Springer 究所/科学出版社）",
    "Cybersecurity Springer 究所/科学出版社）",
    "DASFAA",
    "DASFAA International Conference on Database Systems for Advanced Applications",
    "Data & Knowledge Engineering",
    "Data Compression Conference",
    "Data Mining and Knowledge Discovery",
    "Data Science and Engineering CCF/ Springer Nature",
    "DATE",
    "DATE Design, Automation & Test in Europe IEEE/",
    "DCC",
    "DCC Data Compression Conference",
    "Design, Automation & Test in Europe IEEE/",
    "Designs, Codes and Cryptography",
    "DKE",
    "DKE Data & Knowledge Engineering",
    "DMKD",
    "DMKD Data Mining and Knowledge Discovery",
    "DSE",
    "DSE Data Science and Engineering CCF/ Springer Nature",
    "DSN",
    "DSN International Conference on Dependable Systems and Networks IEEE/ IFIP",
    "ECAI",
    "ECAI European Conference on Artificial Intelligence",
    "ECCV",
    "ECCV European Conference on Computer Vision",
    "ECML-PKDD",
    "ECML-PKDD European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases",
    "ECOOP",
    "ECOOP European Conference on Object-Oriented Programming AITO",
    "ECSCW",
    "ECSCW European Conference on Computer Supported Cooperative Work",
    "EDBT",
    "EDBT International Conference on Extending Database Technology",
    "EGSR",
    "EGSR Eurographics Symposium on Rendering Wiley/ Blackwell",
    "EJIS",
    "EJIS European Journal of Information Systems",
    "EMNLP",
    "EMNLP Conference on Empirical Methods in Natural Language Processing ACL",
    "Empirical Software Engineering",
    "EMSOFT",
    "EMSOFT International Conference on Embedded Software IEEE/ACM /IFIP",
    "ESA",
    "ESA European Symposium on Algorithms",
    "ESE",
    "ESE Empirical Software Engineering",
    "ESEM",
    "ESEM International Symposium on Empirical Software Engineering and Measurement IEEE/",
    "ESORICS",
    "ESORICS European Symposium on Research in Computer Security",
    "ETAPS",
    "ETAPS European Joint Conferences on Theory and Practice of Software",
    "Euro-Par",
    "Euro-Par European Conference on Parallel and Distributed Computing Springer",
    "Eurographics",
    "Eurographics Annual Conference of the European Association for Computer Graphics Wiley/ Blackwell",
    "Eurographics Conference on Visualization",
    "Eurographics Symposium on Geometry Processing Wiley/ Blackwell",
    "Eurographics Symposium on Rendering Wiley/ Blackwell",
    "European Conference on Artificial Intelligence",
    "European Conference on Computer Supported Cooperative Work",
    "European Conference on Computer Vision",
    "European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases",
    "European Conference on Object-Oriented Programming AITO",
    "European Conference on Parallel and Distributed Computing Springer",
    "European Joint Conferences on Theory and Practice of Software",
    "European Journal of Information Systems",
    "European Symposium on Algorithms",
    "European Symposium on Research in Computer Security",
    "EuroVis",
    "EuroVis Eurographics Conference on Visualization",
    "Evaluation: An International Journal",
    "Evolutionary",
    "Evolutionary Computation",
    "FAC",
    "FAC Formal Aspects of Computing",
    "Fast Software Encryption",
    "FCS",
    "FCS Frontiers of Computer Science Higher Education Press",
    "FMCAD",
    "FMCAD Formal Methods in Computer-Aided Design",
    "FMSD",
    "FMSD Formal Methods in System Design",
    "Formal Aspects of Computing",
    "Formal Methods in Computer-Aided Design",
    "Formal Methods in System Design",
    "FPGA",
    "FPGA ACM/SIGDA International Symposium on Field-Programmable Gate Arrays",
    "Frontiers of Computer Science Higher Education Press",
    "FSE",
    "FSE Fast Software Encryption",
    "GeoInformatica",
    "GROUP",
    "GROUP ACM International Conference on Supporting Group Work",
    "HCI",
    "HCI Human-Computer Interaction",
    "HiPEAC",
    "HiPEAC International Conference on High Performance and Embedded Architectures and Compilers",
    "HOT",
    "HOT CHIPS Hot Chips: A Symposium on High Performance Chips",
    "HotOS",
    "HotOS USENIX Workshop on Hot Topics in Operating Systems",
    "HSCC",
    "HSCC International Conference on Hybrid Systems: Computation and Control Springer/",
    "Human-Computer Interaction",
    "I3D",
    "I3D ACM SIGGRAPH Symposium on Interactive 3D Graphics and Games",
    "ICALP",
    "ICALP International Colloquium on Automata, Languages and Programming",
    "ICAPS",
    "ICAPS International Conference on Automated Planning and Scheduling",
    "ICASSP",
    "ICASSP IEEE International Conference on Acoustics, Speech and Signal Processing",
    "ICCAD",
    "ICCAD International Conference on Computer-Aided Design IEEE/",
    "ICCD",
    "ICCD International Conference on Computer Design",
    "ICDCS",
    "ICDCS IEEE International Conference on Distributed Computing Systems",
    "ICDM",
    "ICDM IEEE International Conference on Data Mining",
    "ICDT",
    "ICDT International Conference on Database Theory",
    "ICFP",
    "ICFP ACM SIGPLAN International Conference on Function Programming",
    "ICME",
    "ICME IEEE International Conference on Multimedia & Expo",
    "ICMR",
    "ICMR ACM SIGMM International Conference on Multimedia Retrieval",
    "ICNP",
    "ICNP IEEE International Conference on Network Protocols",
    "ICPC",
    "ICPC IEEE International Conference on Program Comprehension",
    "ICPP",
    "ICPP International Conference on Parallel Processing",
    "ICRA",
    "ICRA IEEE International Conference on Robotics and Automation",
    "ICS",
    "ICS International Conference on Supercomputing",
    "ICSME",
    "ICSME International Conference on Software Maintenance and Evolution",
    "ICSOC",
    "ICSOC International Conference on Service Oriented Computing",
    "ICWS",
    "ICWS IEEE International Conference on Web Services",
    "ICWSM",
    "ICWSM The International AAAI Conference on Web and Social Media",
    "IEEE",
    "IEEE Computer Security Foundations Workshop",
    "IEEE International Conference on Acoustics, Speech and Signal Processing",
    "IEEE International Conference on Bioinformatics and Biomedicine",
    "IEEE International Conference on Cluster Computing",
    "IEEE International Conference on Data Mining",
    "IEEE International Conference on Distributed Computing Systems",
    "IEEE International Conference on Multimedia & Expo",
    "IEEE International Conference on Network Protocols",
    "IEEE International Conference on Pervasive Computing and Communications",
    "IEEE International Conference on Program Comprehension",
    "IEEE International Conference on Robotics and Automation",
    "IEEE International Conference on Sensing, Communication, and Networking",
    "IEEE International Conference on Software Analysis, Evolution, and Reengineering",
    "IEEE International Conference on Web Services",
    "IEEE International Parallel & Distributed Processing Symposium",
    "IEEE International Requirements Engineering Conference",
    "IEEE International Semantic Web Conference",
    "IEEE International Symposium on Circuits and Systems",
    "IEEE International Symposium on Reliable Distributed Systems",
    "IEEE International Symposium on Software Reliability Engineering",
    "IEEE Real-Time and Embedded Technology and Applications Symposium",
    "IEEE Transactions on Affective Computing",
    "IEEE Transactions on Audio, Speech and Language Processing Language Processing）",
    "IEEE Transactions on Automation Science and Engineering",
    "IEEE Transactions on Cloud Computing",
    "IEEE Transactions on Communications",
    "IEEE Transactions on Cybernetics",
    "IEEE Transactions on Evolutionary Computation",
    "IEEE Transactions on Fuzzy Systems",
    "IEEE Transactions on Geoscience and Remote Sensing",
    "IEEE Transactions on Human-Machine Systems",
    "IEEE Transactions on Intelligent Transportation Systems",
    "IEEE Transactions on Medical Imaging",
    "IEEE Transactions on Neural Networks and learning systems",
    "IEEE Transactions on Robotics",
    "IEEE Transactions on Systems, Man,and Cybernetics: Systems",
    "IEEE Transactions on Very Large Scale Integration (VLSI) Systems",
    "IEEE Transactions on Wireless Communications",
    "IEEE/ACM International Workshop on Quality of Service",
    "IEEE/ACM Transactions on Computational Biology and Bioinformatics IEEE/ACM",
    "IET Software",
    "IETS",
    "IETS IET Software",
    "IJAR",
    "IJAR International Journal of Approximate Reasoning",
    "IJCAI",
    "IJCAI International Joint Conference on Artificial Intelligence",
    "IJHCI",
    "IJHCI International Journal of Human-Computer Interaction",
    "IMC",
    "IMC ACM Internet Measurement Conference ACM/",
    "in Bioinformatics",
    "Information",
    "Information and Software Technology",
    "Information Processing and Management",
    "Information Sciences",
    "Information Systems",
    "INFORMS",
    "INFORMS INFORMS Journal on Computing INFORMS",
    "INFORMS Journal on Computing INFORMS",
    "INTER-",
    "INTER- SPEECH Conference of the International Speech Communication Association ISCA",
    "Interacting with Computers",
    "International Colloquium on Automata, Languages and Programming",
    "International Computing and Combinatorics Conference",
    "International Conference on Advanced Information Systems Engineering",
    "International Conference on Automated Planning and Scheduling",
    "International Conference on Compiler Construction",
    "International Conference on Computational Linguistics International Committee on Computational Linguistics",
    "International Conference on Computer Design",
    "International Conference on Computer-Aided Design IEEE/",
    "International Conference on Concurrency Theory",
    "International Conference on Cryptographic Hardware and Embedded Systems",
    "International Conference on Database Systems for Advanced Applications",
    "International Conference on Database Theory",
    "International Conference on Dependable Systems and Networks IEEE/ IFIP",
    "International Conference on Embedded Software IEEE/ACM /IFIP",
    "International Conference on Extending Database Technology",
    "International Conference on High Performance and Embedded Architectures and Compilers",
    "International Conference on Hybrid Systems: Computation and Control Springer/",
    "International Conference on Information Processing in Sensor Networks IEEE/",
    "International conference on Intelligent Systems for Molecular Biology Oxford Journals",
    "International Conference on Medical Image Computing and Computer-Assisted Intervention",
    "International Conference on Parallel Architectures and Compilation Techniques IEEE/",
    "International Conference on Parallel Processing",
    "International Conference on Principles and Practice of Constraint Programming",
    "International Conference on Principles of Knowledge Representation and Reasoning",
    "International Conference on Service Oriented Computing",
    "International Conference on Software Maintenance and Evolution",
    "International Conference on Supercomputing",
    "International Conference on Theory and Applications of Satisfiability Testing",
    "International Conference on Verification, Model Checking and Abstract Interpretation",
    "International Conference on Virtual Execution Environments",
    "International Joint Conference on Artificial Intelligence",
    "International Joint Conference on Autonomous Agents and Multi-agent Systems",
    "International Journal of Approximate Reasoning",
    "International Journal of Human-Computer Interaction",
    "International Middleware Conference ACM/IFIP/",
    "International Static Analysis Symposium",
    "International Symposium on Computational Geometry",
    "International Symposium on Computer Performance, Modeling, Measurements and Evaluation",
    "International Symposium on Empirical Software Engineering and Measurement IEEE/",
    "International Symposium on Mixed and Augmented Reality IEEE/",
    "International Symposium on Recent Advances in Intrusion Detection",
    "International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing IEEE/",
    "International Test Conference",
    "International Workshop on Network and Operating System Support for Digital Audio and Video",
    "International Workshop on Practice and Theory in Public Key Cryptography",
    "IPDPS",
    "IPDPS IEEE International Parallel & Distributed Processing Symposium",
    "IPM",
    "IPM Information Processing and Management",
    "IPSN",
    "IPSN International Conference on Information Processing in Sensor Networks IEEE/",
    "IS",
    "IS Information Systems",
    "ISCAS",
    "ISCAS IEEE International Symposium on Circuits and Systems",
    "ISMAR",
    "ISMAR International Symposium on Mixed and Augmented Reality IEEE/",
    "ISMB",
    "ISMB International conference on Intelligent Systems for Molecular Biology Oxford Journals",
    "ISS",
    "ISS ACM International Conference on Interactive Surfaces and Spaces",
    "ISSRE",
    "ISSRE IEEE International Symposium on Software Reliability Engineering",
    "IST",
    "IST Information and Software Technology",
    "ISWC",
    "ISWC IEEE International Semantic Web Conference",
    "ITC",
    "ITC International Test Conference",
    "IUI",
    "IUI ACM International Conference on Intelligent User Interfaces",
    "IWC",
    "IWC Interacting with Computers",
    "IWQoS",
    "IWQoS IEEE/ACM International Workshop on Quality of Service",
    "JAIR",
    "JAIR Journal of Artificial Intelligence Research",
    "JAMIA",
    "JAMIA Journal of the American Medical Informatics Association BMJ Journals",
    "JASIST",
    "JASIST Journal of the Association for Information Science and Technology",
    "JCS",
    "JCS Journal of Computer Security",
    "JCSS",
    "JCSS Journal of Computer and System Sciences",
    "JCST",
    "JCST Journal of Computer Science and Technology SCIENCE PRESS/Springer",
    "JFP",
    "JFP Journal of Functional Programming",
    "JGO",
    "JGO Journal of Global Optimization",
    "Journal",
    "Journal of Artificial Intelligence Research",
    "Journal of Automated Reasoning",
    "Journal of Computer and System Sciences",
    "Journal of Computer Science and Technology SCIENCE PRESS/Springer",
    "Journal of Computer Security",
    "Journal of Functional Programming",
    "Journal of Global Optimization",
    "Journal of Parallel and Distributed Computing",
    "Journal of Software: Evolution and Process",
    "Journal of Speech, Language, and Hearing Research American Speech- Language Hearing Association",
    "Journal of Symbolic Computation",
    "Journal of Systems and Software",
    "Journal of Systems Architecture: Embedded Software Design",
    "Journal of the American Medical Informatics Association BMJ Journals",
    "Journal of the Association for Information Science and Technology",
    "Journal of Web Semantics",
    "JPDC",
    "JPDC Journal of Parallel and Distributed Computing",
    "JSA",
    "JSA Journal of Systems Architecture: Embedded Software Design",
    "JSC",
    "JSC Journal of Symbolic Computation",
    "JSLHR",
    "JSLHR Journal of Speech, Language, and Hearing Research American Speech- Language Hearing Association",
    "JSS",
    "JSS Journal of Systems and Software",
    "JWS",
    "JWS Journal of Web Semantics",
    "KAIS",
    "KAIS Knowledge and Information Systems",
    "Knowledge and Information Systems",
    "KR",
    "KR International Conference on Principles of Knowledge Representation and Reasoning",
    "Large Installation System Administration Conference",
    "LCTES",
    "LCTES ACM SIGPLAN/SIGBED International Conference on Languages, Compilers and Tools for Embedded Systems",
    "Learning",
    "Linguistics",
    "LISA",
    "LISA Large Installation System Administration Conference",
    "Machine",
    "Machine Learning",
    "Mass Storage Systems and Technologies",
    "Mathematical Structures in Computer Science",
    "METRICS International Conference on Measurement and Modeling of Computer Systems",
    "MICCAI",
    "MICCAI International Conference on Medical Image Computing and Computer-Assisted Intervention",
    "Middleware",
    "Middleware International Middleware Conference ACM/IFIP/",
    "MobiHoc",
    "MobiHoc International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing IEEE/",
    "MobileHCI",
    "MobileHCI ACM International Conference on Mobile Human- Computer Interaction",
    "MobiSys",
    "MobiSys ACM International Conference on Mobile Systems, Applications, and Services",
    "MoDELS",
    "MoDELS ACM/IEEE International Conference on Model Driven EngineeringLanguages and Systems IEEE/",
    "MSCS",
    "MSCS Mathematical Structures in Computer Science",
    "MSST",
    "MSST Mass Storage Systems and Technologies",
    "NAACL",
    "NAACL North American Chapter of the Association for Computational Linguistics Association for Computational Linguistics",
    "Networks",
    "Neural",
    "Neural Computation",
    "Neural Networks",
    "North American Chapter of the Association for Computational Linguistics Association for Computational Linguistics",
    "NOSSDAV",
    "NOSSDAV International Workshop on Network and Operating System Support for Digital Audio and Video",
    "of Automated Reasoning",
    "of Software: Evolution and Process",
    "Pacific Conference onComputer Graphics and Applications Wiley/ Blackwell",
    "PACT",
    "PACT International Conference on Parallel Architectures and Compilation Techniques IEEE/",
    "Parallel",
    "Parallel Computing",
    "Pattern Recognition",
    "PERCOM",
    "PERCOM IEEE International Conference on Pervasive Computing and Communications",
    "Performance",
    "Performance Evaluation: An International Journal",
    "Performance International Symposium on Computer Performance, Modeling, Measurements and Evaluation",
    "PG",
    "PG Pacific Conference onComputer Graphics and Applications Wiley/ Blackwell",
    "PKC",
    "PKC International Workshop on Practice and Theory in Public Key Cryptography",
    "PLOS",
    "PLOS Computational Biology Public Library of Science",
    "PODC",
    "PODC ACM Symposium on Principles of Distributed Computing",
    "PODS",
    "PODS ACM SIGMOD-SIGACT-SIGAI Symposium on Principles of Database Systems",
    "PR",
    "PR Pattern Recognition",
    "RAID",
    "RAID International Symposium on Recent Advances in Intrusion Detection",
    "RE",
    "RE IEEE International Requirements Engineering Conference",
    "RE Requirements Engineering",
    "RECOMB",
    "RECOMB Annual International Conference on Research in Computational Molecular Biology",
    "Requirements Engineering",
    "RTAS",
    "RTAS IEEE Real-Time and Embedded Technology and Applications Symposium",
    "SANER",
    "SANER IEEE International Conference on Software Analysis, Evolution, and Reengineering",
    "SAS",
    "SAS International Static Analysis Symposium",
    "SAT",
    "SAT International Conference on Theory and Applications of Satisfiability Testing",
    "SCA",
    "SCA ACM SIGGRAPH/Eurographics Symposium on Computer Animation",
    "Science of Computer Programming",
    "Sciences",
    "SCP",
    "SCP Science of Computer Programming",
    "SDM",
    "SDM SIAM International Conference on Data Mining",
    "SECON",
    "SECON IEEE International Conference on Sensing, Communication, and Networking",
    "SenSys",
    "SenSys ACM Conference on Embedded Networked Sensor Systems",
    "SGP",
    "SGP Eurographics Symposium on Geometry Processing Wiley/ Blackwell",
    "SIAM International Conference on Data Mining",
    "SIG-",
    "SIG- METRICS International Conference on Measurement and Modeling of Computer Systems",
    "SoCC",
    "SoCC ACM Symposium on Cloud Computing",
    "SoCG",
    "SoCG International Symposium on Computational Geometry",
    "Software and Systems Modeling",
    "Software Testing, Verification and Reliability",
    "Software: Practice and Experience",
    "SoSyM",
    "SoSyM Software and Systems Modeling",
    "SPAA",
    "SPAA ACM Symposium on Parallelism in Algorithms and Architectures",
    "SPE",
    "SPE Software: Practice and Experience",
    "SPEECH Conference of the International Speech Communication Association ISCA",
    "SPM",
    "SPM Symposium on Solid and Physical Modeling SMA/",
    "SRDS",
    "SRDS IEEE International Symposium on Reliable Distributed Systems",
    "STVR",
    "STVR Software Testing, Verification and Reliability",
    "Symposium on Solid and Physical Modeling SMA/",
    "TAAS",
    "TAAS ACM Transactions on Autonomous and Adaptive Systems",
    "TAC",
    "TAC IEEE Transactions on Affective Computing",
    "TACL",
    "TACL Transactions of the Association for Computational Linguistics The Association for Computational Linguistics",
    "TALG",
    "TALG ACM Transactions on Algorithms",
    "TAP",
    "TAP ACM Transactions on Applied Perception",
    "TASAE",
    "TASAE IEEE Transactions on Automation Science and Engineering",
    "TASLP",
    "TASLP IEEE Transactions on Audio, Speech and Language Processing Language Processing）",
    "TCBB",
    "TCBB IEEE/ACM Transactions on Computational Biology and Bioinformatics IEEE/ACM",
    "TCC",
    "TCC IEEE Transactions on Cloud Computing",
    "TCC Theory of Cryptography Conference",
    "TCOM",
    "TCOM IEEE Transactions on Communications",
    "TCS",
    "TCS Theoretical Computer Science",
    "TEC",
    "TEC IEEE Transactions on Evolutionary Computation",
    "TECS",
    "TECS ACM Transactions on Embedded Computing Systems",
    "TFS",
    "TFS IEEE Transactions on Fuzzy Systems",
    "TGARS",
    "TGARS IEEE Transactions on Geoscience and Remote Sensing",
    "The",
    "The Computer Journal",
    "The International AAAI Conference on Web and Social Media",
    "The International Symposium on Code Generation and Optimization IEEE/",
    "The Web Conference",
    "Theoretical Computer Science",
    "Theory of Cryptography Conference",
    "TITS",
    "TITS IEEE Transactions on Intelligent Transportation Systems",
    "TKDD",
    "TKDD ACM Transactions on Knowledge Discovery from Data",
    "TMI",
    "TMI IEEE Transactions on Medical Imaging",
    "TNNLS",
    "TNNLS IEEE Transactions on Neural Networks and learning systems",
    "TOCL",
    "TOCL ACM Transactions on Computational Logic",
    "TODAES",
    "TODAES ACM Transactions on Design Automation of Electronic Systems",
    "TOIT",
    "TOIT ACM Transactions on Internet Technology",
    "TOMM",
    "TOMM ACM Transactions on Multimedia Computing, Communications and Applications",
    "TOMS",
    "TOMS ACM Transactions on Mathematical Software",
    "TOPS",
    "TOPS ACM Transactions on Privacy and Security",
    "TOSN",
    "TOSN ACM Transactions on Sensor Networks",
    "TPCI CCF Transactions on Pervasive Computing and Interaction CCF/",
    "TR",
    "TR IEEE Transactions on Robotics",
    "Transactions of the Association for Computational Linguistics The Association for Computational Linguistics",
    "Transactions on Cybernetics",
    "Transactions on Human-Machine Systems",
    "TRETS",
    "TRETS ACM Transactions on Reconfigurable Technology and Systems",
    "TSMC",
    "TSMC IEEE Transactions on Systems, Man,and Cybernetics: Systems",
    "TVLSI",
    "TVLSI IEEE Transactions on Very Large Scale Integration (VLSI) Systems",
    "TWC",
    "TWC IEEE Transactions on Wireless Communications",
    "TWEB",
    "TWEB ACM Transactions on the Web",
    "UAI",
    "UAI Conference on Uncertainty in Artificial Intelligence AUAI",
    "UMUAI",
    "UMUAI User Modeling and User-Adapted Interaction",
    "USENIX Workshop on Hot Topics in Operating Systems",
    "User Modeling and User-Adapted Interaction",
    "VEE",
    "VEE International Conference on Virtual Execution Environments",
    "VMCAI",
    "VMCAI International Conference on Verification, Model Checking and Abstract Interpretation",
    "Web Information Systems Engineering Conference",
    "WINE",
    "WINE Conference on Web and Internet Economics",
    "WISE",
    "WISE Web Information Systems Engineering Conference",
    "WSDM",
    "WSDM ACM International Conference on Web Search and Data Mining",
    "WWW",
    "WWW The Web Conference",
  ],
  C: [
    "3DV",
    "3DV International Conference on 3D Vision",
    "ACCV",
    "ACCV Asian Conference on Computer Vision",
    "ACISP",
    "ACISP Australasia Conference on Information Security and Privacy",
    "ACM Asia Conference on Computer and Communications Security",
    "ACM Conference on Security and Privacy in Wireless and Mobile Networks",
    "ACM Interaction Design and Children",
    "ACM International Conference on Computing Frontiers",
    "ACM International Conference on Multimodal Interaction",
    "ACM International Systems and Storage Conference",
    "ACM Journal on Emerging Technologies in Computing Systems",
    "ACM SIGCHI Conference on Designing Interactive Systems",
    "ACM SIGPLAN Workshop on Partial Evaluation and Program Manipulation",
    "ACM Special Interest Group on Spatial Information",
    "ACM Symposium on Access Control Models and Technologies",
    "ACM Symposium on Virtual Reality Software and Technology",
    "ACM The Workshop on Hot Topics in Networks",
    "ACM Transactions in Quantum Computing",
    "ACM Transactions on Asian and Low-Resource Language Information Processing",
    "ACM Transactions on Computing Education",
    "ACM Transactions on Computing for Healthcare",
    "ACM Transactions on Cyber-Physical Systems",
    "ACM Transactions on Evolutionary Learning and Optimization",
    "ACM Transactions on Human-Robot Interaction",
    "ACM Transactions on Intelligent Systems and Technology",
    "ACM Transactions on Interactive Intelligent Systems",
    "ACM Transactions on Internet of Things",
    "ACM Transactions on Recommender Systems",
    "ACM Workshop on Digital Rights Management",
    "ACM Workshop on Information Hiding and Multimedia Security",
    "ACM/IEEE International Symposium on Networks-on-Chip IEEE/",
    "ACM/IEEE Symposium on Architectures for Networking and Communication Systems IEEE/",
    "ACM/IEEE Symposium on Edge Computing IEEE/",
    "ACML",
    "ACML Asian Conference on Machine Learning JMLR",
    "ACMSIGPLAN-SIGSOFT Workshop on Program Analysis for Software Tools and Engineering",
    "ACNS",
    "ACNS International Conference on Applied Cryptography and Network Security",
    "ACTA",
    "ACTA Acta Informatica",
    "Acta Informatica",
    "Ad",
    "Ad Hoc Networks",
    "ADMA",
    "ADMA International Conference on Advanced Data Mining and Applications",
    "Advances in Financial Technologies",
    "AFT",
    "AFT Advances in Financial Technologies",
    "AIM",
    "AIM Artificial Intelligence in Medicine",
    "AISTATS",
    "AISTATS International Conference on Artificial Intelligence and Statistics JMLR",
    "ALT",
    "ALT International Conference on Algorithmic Learning Theory",
    "American Medical Informatics Association Annual Symposium AMIA",
    "AMIA",
    "AMIA American Medical Informatics Association Annual Symposium AMIA",
    "ANCS",
    "ANCS ACM/IEEE Symposium on Architectures for Networking and Communication Systems IEEE/",
    "and Computation: Practice and Experience",
    "and Systems",
    "Annals of Pure and Applied Logic",
    "APAL",
    "APAL Annals of Pure and Applied Logic",
    "APBC",
    "APBC Asia Pacific Bioinformatics Conference BioMed Central",
    "APLAS",
    "APLAS Asian Symposium on Programming Languages and Systems",
    "APNet",
    "APNet Asia-Pacific Workshop on Networking",
    "APNOMS",
    "APNOMS Asia-Pacific Network Operations and Management Symposium IFIP/",
    "Applied",
    "Applied Intelligence",
    "APPT",
    "APPT International Symposium on Advanced Parallel Processing Technology",
    "APSEC",
    "APSEC Asia-Pacific Software Engineering Conference",
    "APWeb",
    "APWeb Asia Pacific Web Conference",
    "Artificial",
    "Artificial Intelligence in Medicine",
    "Artificial Life",
    "ASAP",
    "ASAP IEEE International Conference on Application-Specific Systems, Architectures, and Processors",
    "Asia and South Pacific Design Automation Conference IEEE/",
    "Asia Pacific Bioinformatics Conference BioMed Central",
    "Asia Pacific Web Conference",
    "Asia-Pacific Network Operations and Management Symposium IFIP/",
    "Asia-Pacific Software Engineering Conference",
    "Asia-Pacific Symposium on Internetware",
    "Asia-Pacific Workshop on Networking",
    "AsiaCCS",
    "AsiaCCS ACM Asia Conference on Computer and Communications Security",
    "Asian Conference on Computer Vision",
    "Asian Conference on Machine Learning JMLR",
    "Asian Symposium on Programming Languages and Systems",
    "ASP-DAC",
    "ASP-DAC Asia and South Pacific Design Automation Conference IEEE/",
    "ASRU",
    "ASRU Automatic Speech Recognition and Understanding Workshop IEEE SLTC",
    "ASSETS",
    "ASSETS International ACM SIGACCESS Conference on Computers and Accessibility",
    "ATS",
    "ATS IEEE Asian Test Symposium",
    "ATVA",
    "ATVA International Symposium on Automated Technology for Verification and Analysis",
    "Australasia Conference on Information Security and Privacy",
    "Automatic Speech Recognition and Understanding Workshop IEEE SLTC",
    "AVI",
    "AVI International Working Conference on Advanced Visual Interfaces",
    "Behaviour & Information Technology",
    "BigData IEEE International Conference on Big Data",
    "Bioinformatics BioMed Central",
    "BIT",
    "BIT Behaviour & Information Technology",
    "BlockSys",
    "BlockSys International Conference on Blockchain, Artificial Intelligence, and Trustworthy Systems",
    "BMC",
    "BMC Bioinformatics BioMed Central",
    "BMVC",
    "BMVC British Machine Vision Conference British Machine Vision Association",
    "British Machine Vision Conference British Machine Vision Association",
    "C&G",
    "C&G Computers & Graphics",
    "CAD/Graphics",
    "CAD/Graphics International Conference on Computer-Aided Design and Computer Graphics Processing",
    "CASAXR",
    "CASAXR International Conference on Computer Animation, Social Agents, and Extended Reality",
    "CASES",
    "CASES International Conference on Compilers, Architectures, and Synthesis for Embedded Systems",
    "CAVW",
    "CAVW Computer animation & virtual worlds",
    "CC",
    "CC Computer Communications",
    "CCF International Conference on Extended Reality",
    "CCF International Conference on Natural Language Processing and Chinese Computing",
    "CCF-",
    "CCF- THPC CCF Transactions on High Performance Computing CCF",
    "CCGRID",
    "CCGRID IEEE/ACM International Symposium on Cluster, Cloud and Grid Computing IEEE/",
    "CEC Congress on Evolutionary Computation",
    "CF",
    "CF ACM International Conference on Computing Frontiers",
    "CGI",
    "CGI Computer Graphics International",
    "CGTA",
    "CGTA Computational Geometry: Theory and Applications",
    "CL",
    "CL Computer Languages, Systems and Structures",
    "CLOUD IEEE International Conference on Cloud Computing",
    "CLSR",
    "CLSR Computer Law & Security Review",
    "CODASPY",
    "CODASPY Conference on Data and Application Security and Privacy",
    "CollaborateCom",
    "CollaborateCom International Conference on Collaborative Computing: Networking, Applications and Worksharing",
    "Communications",
    "COMPSAC",
    "COMPSAC International Computer Software and Applications Conference",
    "Computational",
    "Computational Geometry: Theory and Applications",
    "Computational Intelligence",
    "Computational Visual Media Tsinghua University",
    "Computer",
    "Computer animation & virtual worlds",
    "Computer Communications",
    "Computer Graphics International",
    "Computer Languages, Systems and Structures",
    "Computer Law & Security Review",
    "Computer Science Logic",
    "Computer Speech & Language",
    "Computers & Graphics",
    "Computing",
    "Concurrency",
    "Concurrency and Computation: Practice and Experience",
    "Conference on Computational Natural Language Learning Association for Computational Linguistics",
    "Conference on Data and Application Security and Privacy",
    "Conference on Detection of Intrusions and Malware & Vulnerability Assessment",
    "Conference on Green, Pervasive and Cloud Computing",
    "CoNLL",
    "CoNLL Conference on Computational Natural Language Learning Association for Computational Linguistics",
    "Connection",
    "Connection Science",
    "CoopIS",
    "CoopIS International Conference on Cooperative Information Systems",
    "COSIT",
    "COSIT International Conference on Spatial Information Theory",
    "CSCloud",
    "CSCloud International Conference on Cyber Security and Cloud Computing IEEE CSCloud Steering Committee",
    "CSCWD",
    "CSCWD International Conference on Computer Supported Cooperative Work in Design",
    "CSL",
    "CSL Computer Science Logic",
    "CT-RSA",
    "CT-RSA The Cryptographer's Track at RSA Conference",
    "CVM",
    "CVM Computational Visual Media Tsinghua University",
    "Cybernetics",
    "Cybernetics and Systems",
    "DAI",
    "DAI International Conference on Distributed Artificial Intelligence ACM/",
    "DAM",
    "DAM Discrete Applied Mathematics",
    "DC",
    "DC Distributed Computing",
    "DCG",
    "DCG Discrete & Computational Geometry",
    "Decision Support Systems",
    "DEXA",
    "DEXA International Conference on Database and Expert System Applications",
    "DFRWS",
    "DFRWS Digital Forensic Research Workshop",
    "Digital Forensic Research Workshop",
    "DIMVA",
    "DIMVA Conference on Detection of Intrusions and Malware & Vulnerability Assessment",
    "DIS",
    "DIS ACM SIGCHI Conference on Designing Interactive Systems",
    "Discrete & Computational Geometry",
    "Discrete Applied Mathematics",
    "Distributed and Parallel Databases",
    "Distributed Computing",
    "DPD",
    "DPD Distributed and Parallel Databases",
    "DRM",
    "DRM ACM Workshop on Digital Rights Management",
    "DSAA",
    "DSAA IEEE International Conference on Data Science and Advanced Analytics",
    "DSS",
    "DSS Decision Support Systems",
    "EAAI",
    "EAAI Engineering Applications of Artificial Intelligence",
    "EASE",
    "EASE International Conference on Evaluation and Assessment in Software Engineering",
    "ECIR",
    "ECIR European Conference on Information Retrieval",
    "EITEE",
    "EITEE ENGINEERING Information Technology & Electronic Engineering Engineering） 浙江大学出版社 13 TCSS IEEE Transactions on Computational Social Systems",
    "Engineering Applications of Artificial Intelligence",
    "ENGINEERING Information Technology & Electronic Engineering Engineering） 浙江大学出版社 13 TCSS IEEE Transactions on Computational Social Systems",
    "ER",
    "ER International Conference on Conceptual Modeling",
    "ESWA",
    "ESWA Expert Systems with Applications",
    "ESWC",
    "ESWC Extended Semantic Web Conference",
    "ETS",
    "ETS IEEE European Test Symposium",
    "EURASIP",
    "EURASIP Journal on Information Security",
    "European Conference on Information Retrieval",
    "EuroS&P",
    "EuroS&P IEEE European Symposium on Security and Privacy",
    "Expert",
    "Expert Systems Blackwell/",
    "Expert Systems with Applications",
    "Extended Semantic Web Conference",
    "FC",
    "FC Financial Cryptography and Data Security",
    "FCCM",
    "FCCM IEEE Symposium on Field-Programmable Custom Computing Machines",
    "FG",
    "FG IEEE International Conference on Automatic Face and Gesture Recognition",
    "FGCS",
    "FGCS Future Generation Computer Systems",
    "Financial Cryptography and Data Security",
    "FORTE",
    "FORTE International Conference on Formal Techniques for Distributed Objects, Components, and Systems",
    "Foundations of Software Technology and Theoretical Computer Science Indian Association for Research in Computing Science",
    "FPL",
    "FPL International Conference on Field-Programmable Logic and Applications",
    "FPT",
    "FPT International Conference on Field-Programmable Technology",
    "FSCD",
    "FSCD International Conference on Formal Structures for Computation and Deduction Dagstuhl Leibniz LIPIcs",
    "FSTTCS",
    "FSTTCS Foundations of Software Technology and Theoretical Computer Science Indian Association for Research in Computing Science",
    "FUIN",
    "FUIN Fundamenta Informaticae",
    "Fundamenta Informaticae",
    "Future Generation Computer Systems",
    "Fuzzy",
    "Fuzzy Sets and Systems",
    "GECCO",
    "GECCO Genetic and Evolutionary Computation Conference",
    "Genetic and Evolutionary Computation Conference",
    "Geometric Modeling and Processing",
    "Geoscience and Remote Sensing Letters",
    "GI",
    "GI Graphics Interface",
    "GLOBECOM",
    "GLOBECOM IEEE Global Communications Conference",
    "GLSVLSI",
    "GLSVLSI Great Lakes Symposium on VLSI IEEE/",
    "GMOD",
    "GMOD Graphical Models",
    "GMP",
    "GMP Geometric Modeling and Processing",
    "GPC",
    "GPC Conference on Green, Pervasive and Cloud Computing",
    "Graphical Models",
    "Graphics Interface",
    "Great Lakes Symposium on VLSI IEEE/",
    "HCC",
    "HCC High-Confidence Computing",
    "HEALTH",
    "HEALTH ACM Transactions on Computing for Healthcare",
    "High-Confidence Computing",
    "HiPC",
    "HiPC IEEE International Conference on High Performance Computing, Data and Analytics IEEE/",
    "Hoc Networks",
    "HOTI",
    "HOTI IEEE Symposium on High-Performance Interconnects",
    "HotNets",
    "HotNets ACM The Workshop on Hot Topics in Networks",
    "HotSec",
    "HotSec USENIX Workshop on Hot Topics in Security",
    "HotStorage",
    "HotStorage HotStorage USENIX Association",
    "HotStorage USENIX Association",
    "HPCC",
    "HPCC IEEE International Conference on High Performance Computing and Communications",
    "I&M",
    "I&M Information & Management",
    "ICA3PP",
    "ICA3PP International Conference on Algorithms and Architectures for Parallel Processing",
    "ICANN",
    "ICANN International Conference on Artificial Neural Networks",
    "ICC",
    "ICC IEEE International Conference on Communications",
    "ICCCN",
    "ICCCN IEEE International Conference on Computer Communications and Networks",
    "ICDAR",
    "ICDAR International Conference on Document Analysis and Recognition",
    "ICDF2C",
    "ICDF2C International Conference on Digital Forensics & Cyber Crime",
    "ICECCS",
    "ICECCS International Conference on Engineering of Complex Computer Systems",
    "ICFEM",
    "ICFEM International Conference on Formal Engineering Methods",
    "ICIC",
    "ICIC International Conference on Intelligent Computing Springer-Nature",
    "ICICS",
    "ICICS International Conference on Information and Communications Security",
    "ICIG",
    "ICIG International Conference on Image and Graphics",
    "ICMI",
    "ICMI ACM International Conference on Multimodal Interaction",
    "ICONIP",
    "ICONIP International Conference on Neural Information Processing",
    "ICPADS",
    "ICPADS International Conference on Parallel and Distributed Systems",
    "ICPR",
    "ICPR International Conference on Pattern Recognition",
    "ICSR",
    "ICSR International Conference on Software Reuse",
    "ICSS",
    "ICSS International Conference on Service Science CCF/Springer",
    "ICSSP",
    "ICSSP International Conference on Software and System Process",
    "ICST",
    "ICST IEEE International Conference on Software Testing, Verification and Validation",
    "ICTAC",
    "ICTAC International Colloquium on Theoretical Aspects of Computing",
    "ICTAI",
    "ICTAI IEEE International Conference on Tools with Artificial Intelligence",
    "ICWE",
    "ICWE International Conference on Web Engineering",
    "ICXR",
    "ICXR CCF International Conference on Extended Reality",
    "IDA",
    "IDA Intelligent Data Analysis",
    "IDC",
    "IDC ACM Interaction Design and Children",
    "IEEE",
    "IEEE Asian Test Symposium",
    "IEEE BigData IEEE International Conference on Big Data",
    "IEEE CEC Congress on Evolutionary Computation",
    "IEEE CLOUD IEEE International Conference on Cloud Computing",
    "IEEE Conference on Local Computer Networks",
    "IEEE European Symposium on Security and Privacy",
    "IEEE European Test Symposium",
    "IEEE Geoscience and Remote Sensing Letters",
    "IEEE Global Communications Conference",
    "IEEE International Conference on Application-Specific Systems, Architectures, and Processors",
    "IEEE International Conference on Automatic Face and Gesture Recognition",
    "IEEE International Conference on Communications",
    "IEEE International Conference on Computer Communications and Networks",
    "IEEE International Conference on Data Science and Advanced Analytics",
    "IEEE International Conference on High Performance Computing and Communications",
    "IEEE International Conference on High Performance Computing, Data and Analytics IEEE/",
    "IEEE International Conference on Mobile Adhoc and Sensor Systems",
    "IEEE International Conference on Peer-to-Peer Computing",
    "IEEE International Conference on Software Services Engineering",
    "IEEE International Conference on Software Testing, Verification and Validation",
    "IEEE International Conference on Systems, Man, and Cybernetics",
    "IEEE International Conference on Tools with Artificial Intelligence",
    "IEEE International Conference on Trust, Security and Privacy in Computing and Communications",
    "IEEE International Conference on Ubiquitous Intelligence and Computing",
    "IEEE International Performance Computing and Communications Conference",
    "IEEE International Symposium on a World of Wireless, Mobile and Multimedia Networks",
    "IEEE International Symposium on Parallel and Distributed Processing with Applications",
    "IEEE International Symposium on Performance Analysis of Systems and Software",
    "IEEE International Working Conference on Source Code Analysis and Manipulation",
    "IEEE Internet of Things Journal",
    "IEEE Journal of Biomedical and Health Informatics",
    "IEEE Pacific Visualization Symposium",
    "IEEE Signal Processing Letters",
    "IEEE Symposium on Computers and Communications",
    "IEEE Symposium on Field-Programmable Custom Computing Machines",
    "IEEE Symposium on High-Performance Interconnects",
    "IEEE Transactions on Big Data",
    "IEEE Transactions on Circuits and Systems I: Regular Papers",
    "IEEE Transactions on Games",
    "IEEE Transactions on Industrial Informatics",
    "IEEE Transactions on Network and Service Management",
    "IEEE Transactions on Reliability",
    "IEEE Transactions on Sustainable Computing",
    "IEEE VLSI Test Symposium",
    "IEEE Wireless Communications and Networking Conference",
    "IEEE World Haptics Conference",
    "IEEE/ACM International Symposium on Cluster, Cloud and Grid Computing IEEE/",
    "IEEE\\RSJ International Conference on Intelligent Robots and Systems",
    "IET",
    "IET Communications",
    "IET Computer Vision",
    "IET Image Processing",
    "IET Information Security",
    "IET Intelligent Transport Systems",
    "IET Signal Processing",
    "IET-CVI",
    "IET-CVI IET Computer Vision",
    "IET-IPR",
    "IET-IPR IET Image Processing",
    "IFIP",
    "IFIP International Conference on Network and Parallel Computing",
    "IFIP International Conferences on Networking IFIP",
    "IFIP International Information Security Conference",
    "IFIP WG 11.9 IFIP Working Group 11.9 International Conference on Digital Forensics",
    "IFIP/IEEE International Symposium on Integrated Network Management IFIP/",
    "IH&MMSec",
    "IH&MMSec ACM Workshop on Information Hiding and Multimedia Security",
    "IJCB",
    "IJCB International Joint Conference on Biometrics",
    "IJCIA",
    "IJCIA International Journal of Computational Intelligence and Applications",
    "IJCNN",
    "IJCNN International Joint Conference on Neural Networks",
    "IJDAR",
    "IJDAR International Journal on Document Analysis and Recognition",
    "IJGIS",
    "IJGIS International Journal of Geographical Information Science",
    "IJICS",
    "IJICS International Journal of Information and Computer Security",
    "IJIS",
    "IJIS International Journal of Intelligent Systems",
    "IJISP",
    "IJISP International Journal of Information Security and Privacy IGI Global",
    "IJKM",
    "IJKM International Journal of Knowledge Management IGI",
    "IJNS",
    "IJNS International Journal of Neural Systems",
    "IJPRAI",
    "IJPRAI International Journal of Pattern Recognition and Artificial Intelligence",
    "IJSEKE",
    "IJSEKE International Journal of Software Engineering and Knowledge Engineering",
    "IJSWIS",
    "IJSWIS International Journal on Semantic Web and Information Systems IGI",
    "IJTCS-FAW",
    "IJTCS-FAW International Joint Conference on Theoretical Computer Science - Frontier of Algorithmic Wisdom",
    "IJUFKS",
    "IJUFKS International Journal of Uncertainty, Fuzziness and Knowledge-Based Systems",
    "ILP",
    "ILP International Conference on Inductive Logic Programming",
    "IM",
    "IM IFIP/IEEE International Symposium on Integrated Network Management IFIP/",
    "IMAGE",
    "Image Analysis",
    "Image and Vision Computing",
    "IMAGE Signal Processing: Image Communication",
    "IMCS",
    "IMCS Information and Computer Security Emerald",
    "Information & Management",
    "Information and Computer Security Emerald",
    "Information Processing Letters",
    "Information Security",
    "Information Security Conference",
    "Inscrypt",
    "Inscrypt International Conference on Information Security and Cryptology",
    "Integration",
    "Integration Integration, the VLSI Journal",
    "Integration, the VLSI Journal",
    "Intelligence",
    "Intelligent Data Analysis",
    "Intelligent Transport Systems",
    "INTERACT",
    "INTERACT International Conference on Human- Computer Interaction of International Federation for Information Processing IFIP",
    "International ACM SIGACCESS Conference on Computers and Accessibility",
    "International Colloquium on Theoretical Aspects of Computing",
    "International Computer Software and Applications Conference",
    "International Conference on 3D Vision",
    "International Conference on Advanced Data Mining and Applications",
    "International Conference on Algorithmic Learning Theory",
    "International Conference on Algorithms and Architectures for Parallel Processing",
    "International Conference on Applied Cryptography and Network Security",
    "International Conference on Artificial Intelligence and Statistics JMLR",
    "International Conference on Artificial Neural Networks",
    "International Conference on Blockchain, Artificial Intelligence, and Trustworthy Systems",
    "International Conference on Collaborative Computing: Networking, Applications and Worksharing",
    "International Conference on Compilers, Architectures, and Synthesis for Embedded Systems",
    "International Conference on Computer Animation, Social Agents, and Extended Reality",
    "International Conference on Computer Supported Cooperative Work in Design",
    "International Conference on Computer-Aided Design and Computer Graphics Processing",
    "International Conference on Conceptual Modeling",
    "International Conference on Cooperative Information Systems",
    "International Conference on Cyber Security and Cloud Computing IEEE CSCloud Steering Committee",
    "International Conference on Database and Expert System Applications",
    "International Conference on Digital Forensics & Cyber Crime",
    "International Conference on Distributed Artificial Intelligence ACM/",
    "International Conference on Document Analysis and Recognition",
    "International Conference on Engineering of Complex Computer Systems",
    "International Conference on Evaluation and Assessment in Software Engineering",
    "International Conference on Field-Programmable Logic and Applications",
    "International Conference on Field-Programmable Technology",
    "International Conference on Formal Engineering Methods",
    "International Conference on Formal Methods and Models for Co-Design IEEE/",
    "International Conference on Formal Structures for Computation and Deduction Dagstuhl Leibniz LIPIcs",
    "International Conference on Formal Techniques for Distributed Objects, Components, and Systems",
    "International Conference on Human- Computer Interaction of International Federation for Information Processing IFIP",
    "International Conference on Image and Graphics",
    "International Conference on Inductive Logic Programming",
    "International Conference on Information and Communications Security",
    "International Conference on Information Security and Cryptology",
    "International Conference on Integer Programming and Combinatorial Optimization",
    "International Conference on Intelligent Computing Springer-Nature",
    "International conference on Knowledge Science, Engineering and Management",
    "International Conference on Mathematical Foundations of Computer Science",
    "International Conference on Mobile and Ubiquitous Systems: Computing, Networking and Services",
    "International Conference on Mobile Data Management",
    "International Conference on Mobility, Sensing and Networking",
    "International Conference on Modeling, Analysis and Simulation of Wireless and Mobile Systems",
    "International Conference on Multimedia Modeling",
    "International Conference on Networking, Architecture and Storages",
    "International Conference on Neural Information Processing",
    "International Conference on Parallel and Distributed Systems",
    "International Conference on Pattern Recognition",
    "International Conference on Runtime Verification",
    "International Conference on Scientific and Statistical Database Management",
    "International Conference on Security and Privacy in Communication Networks",
    "International Conference on Service Science CCF/Springer",
    "International Conference on Software and System Process",
    "International Conference on Software Engineering and Knowledge Engineering KSI",
    "International Conference on Software Quality, Reliability and Security",
    "International Conference on Software Reuse",
    "International Conference on Spatial Information Theory",
    "International Conference on Web Age Information Management",
    "International Conference on Web Engineering",
    "International Joint Conference on Biometrics",
    "International Joint Conference on Neural Networks",
    "International Joint Conference on Theoretical Computer Science - Frontier of Algorithmic Wisdom",
    "International Journal of Computational Intelligence and Applications",
    "International Journal of Geographical Information Science",
    "International Journal of Information and Computer Security",
    "International Journal of Information Security and Privacy IGI Global",
    "International Journal of Intelligent Systems",
    "International Journal of Knowledge Management IGI",
    "International Journal of Neural Systems",
    "International Journal of Pattern Recognition and Artificial Intelligence",
    "International Journal of Software Engineering and Knowledge Engineering",
    "International Journal of Software Tools for Technology Transfer",
    "International Journal of Uncertainty, Fuzziness and Knowledge-Based Systems",
    "International Journal on Document Analysis and Recognition",
    "International Journal on Semantic Web and Information Systems IGI",
    "International Symposium on Advanced Parallel Processing Technology",
    "International Symposium on Algorithmic Game Theory",
    "International Symposium on Algorithms and Computation",
    "International Symposium on Automated Technology for Verification and Analysis",
    "International Symposium on Bioinformatics Research and Applications",
    "International Symposium on Logic-based Program Synthesis and Transformation",
    "International Symposium on Low Power Electronics and Design IEEE/",
    "International Symposium on Model Checking of Software",
    "International Symposium on Modeling, Analysis, and Simulation of Computer and Telecommunication Systems",
    "International Symposium on Physical Design",
    "International Symposium on Spatial and Temporal Databases",
    "International Test Conference in Asia",
    "International Working Conference on Advanced Visual Interfaces",
    "International Workshop on Web and Databases",
    "Internetware",
    "Internetware Asia-Pacific Symposium on Internetware",
    "IOT",
    "IOT IEEE Internet of Things Journal",
    "IPCCC",
    "IPCCC IEEE International Performance Computing and Communications Conference",
    "IPCO",
    "IPCO International Conference on Integer Programming and Combinatorial Optimization",
    "IPL",
    "IPL Information Processing Letters",
    "IROS",
    "IROS IEEE\\RSJ International Conference on Intelligent Robots and Systems",
    "ISAAC",
    "ISAAC International Symposium on Algorithms and Computation",
    "ISBRA",
    "ISBRA International Symposium on Bioinformatics Research and Applications",
    "ISC",
    "ISC Information Security Conference",
    "ISCC",
    "ISCC IEEE Symposium on Computers and Communications",
    "ISLPED",
    "ISLPED International Symposium on Low Power Electronics and Design IEEE/",
    "ISPA",
    "ISPA IEEE International Symposium on Parallel and Distributed Processing with Applications",
    "ISPASS",
    "ISPASS IEEE International Symposium on Performance Analysis of Systems and Software",
    "ISPD",
    "ISPD International Symposium on Physical Design",
    "ITC-Asia",
    "ITC-Asia International Test Conference in Asia",
    "IVC",
    "IVC Image and Vision Computing",
    "JBHI",
    "JBHI IEEE Journal of Biomedical and Health Informatics",
    "JCIS",
    "JCIS Journal of Computer Information Systems IACIS",
    "JCOMPLEXI",
    "JCOMPLEXI TY Journal of Complexity",
    "JDM",
    "JDM Journal of Database Management IGI-Global",
    "JETAI",
    "JETAI Journal of Experimental and Theoretical Artificial Intelligence",
    "JETC",
    "JETC ACM Journal on Emerging Technologies in Computing Systems",
    "JETTA",
    "JETTA Journal of Electronic Testing-Theory and Applications",
    "JGC",
    "JGC Journal of Grid computing",
    "JGITM",
    "JGITM Journal of Global Information Technology Management Ivy League Publishing",
    "JIIS",
    "JIIS Journal of Intelligent Information Systems",
    "JISA",
    "JISA Journal of Information Security and Applications",
    "JLAMP",
    "JLAMP Journal of Logical and Algebraic Methods in Programming",
    "JNCA",
    "JNCA Journal of Network and Computer Applications",
    "Journal of Computer Information Systems IACIS",
    "Journal of Database Management IGI-Global",
    "Journal of Electronic Testing-Theory and Applications",
    "Journal of Experimental and Theoretical Artificial Intelligence",
    "Journal of Global Information Technology Management Ivy League Publishing",
    "Journal of Grid computing",
    "Journal of Information Security and Applications",
    "Journal of Intelligent Information Systems",
    "Journal of Logic and Computation",
    "Journal of Logical and Algebraic Methods in Programming",
    "Journal of Network and Computer Applications",
    "Journal of Visual Communication and Image Representation",
    "Journal of Web Engineering",
    "Journal on Information Security",
    "JSIS",
    "JSIS The Journal of Strategic Information Systems",
    "JSL",
    "JSL The Journal of Symbolic Logic Association for Symbolic Logic",
    "JVCIR",
    "JVCIR Journal of Visual Communication and Image Representation",
    "JWE",
    "JWE Journal of Web Engineering",
    "KBS",
    "KBS Knowledge-Based Systems",
    "Knowledge-Based Systems",
    "KSEM",
    "KSEM International conference on Knowledge Science, Engineering and Management",
    "LCN",
    "LCN IEEE Conference on Local Computer Networks",
    "Life",
    "LMCS",
    "LMCS Logical Methods in Computer Science LMCS",
    "LOGCOM",
    "LOGCOM Journal of Logic and Computation",
    "Logical Methods in Computer Science LMCS",
    "LOPSTR",
    "LOPSTR International Symposium on Logic-based Program Synthesis and Transformation",
    "Machine",
    "Machine Translation",
    "Machine Vision and Applications",
    "MASCOTS",
    "MASCOTS International Symposium on Modeling, Analysis, and Simulation of Computer and Telecommunication Systems",
    "MASS",
    "MASS IEEE International Conference on Mobile Adhoc and Sensor Systems",
    "MDM",
    "MDM International Conference on Mobile Data Management",
    "Medical",
    "Medical Image Analysis",
    "MEMOCODE",
    "MEMOCODE International Conference on Formal Methods and Models for Co-Design IEEE/",
    "MFCS",
    "MFCS International Conference on Mathematical Foundations of Computer Science",
    "Mining Software Repositories IEEE/",
    "MMM",
    "MMM International Conference on Multimedia Modeling",
    "Mobile Networks and Applications",
    "MobiQuitous",
    "MobiQuitous International Conference on Mobile and Ubiquitous Systems: Computing, Networking and Services",
    "MONET",
    "MONET Mobile Networks and Applications",
    "MS",
    "MS Multimedia Systems",
    "MSN",
    "MSN International Conference on Mobility, Sensing and Networking",
    "MSR",
    "MSR Mining Software Repositories IEEE/",
    "MSWiM",
    "MSWiM International Conference on Modeling, Analysis and Simulation of Wireless and Mobile Systems",
    "MTA",
    "MTA Multimedia Tools and Applications",
    "Multimedia Systems",
    "Multimedia Tools and Applications",
    "NAS",
    "NAS International Conference on Networking, Architecture and Storages",
    "National Conference on Man-Machine Speech Communication CCF/中国中 文信息学会",
    "Natural",
    "Natural Computing",
    "Natural Language Engineering",
    "NCA",
    "NCA Neural Computing and Applications",
    "NCMMSC",
    "NCMMSC National Conference on Man-Machine Speech Communication CCF/中国中 文信息学会",
    "Networking",
    "Networking IFIP International Conferences on Networking IFIP",
    "Networks",
    "Neural Computing and Applications",
    "Neural Processing Letters",
    "Neurocomputing",
    "New Security Paradigms Workshop",
    "NLE",
    "NLE Natural Language Engineering",
    "NLPCC",
    "NLPCC CCF International Conference on Natural Language Processing and Chinese Computing",
    "NOCS",
    "NOCS ACM/IEEE International Symposium on Networks-on-Chip IEEE/",
    "NPC",
    "NPC IFIP International Conference on Network and Parallel Computing",
    "NPL",
    "NPL Neural Processing Letters",
    "NSPW",
    "NSPW New Security Paradigms Workshop",
    "of Computing Systems",
    "P2P",
    "P2P IEEE International Conference on Peer-to-Peer Computing",
    "PAA",
    "PAA Pattern Analysis and Applications",
    "Pacific Rim International Conference on Artificial Intelligence",
    "Pacific-Asia Conference on Knowledge Discovery and Data Mining",
    "PacificVis",
    "PacificVis IEEE Pacific Visualization Symposium",
    "PACM",
    "PACM PL Proceedings of the ACM on Programming Languages",
    "PACMHCI",
    "PACMHCI Proceedings of the ACM on Human-Computer Interaction",
    "PAKDD",
    "PAKDD Pacific-Asia Conference on Knowledge Discovery and Data Mining",
    "PAM",
    "PAM Passive and Active Measurement Conference",
    "Passive and Active Measurement Conference",
    "PASTE",
    "PASTE ACMSIGPLAN-SIGSOFT Workshop on Program Analysis for Software Tools and Engineering",
    "Pattern Analysis and Applications",
    "Pattern Recognition Letters",
    "Peer-to-Peer Networking and Applications",
    "PEPM",
    "PEPM ACM SIGPLAN Workshop on Partial Evaluation and Program Manipulation",
    "Personal and Ubiquitous Computing",
    "Pervasive and Mobile Computing",
    "PETS",
    "PETS Privacy Enhancing Technologies Symposium",
    "PL Proceedings of the ACM on Programming Languages",
    "PMC",
    "PMC Pervasive and Mobile Computing",
    "PPNA",
    "PPNA Peer-to-Peer Networking and Applications",
    "PRICAI",
    "PRICAI Pacific Rim International Conference on Artificial Intelligence",
    "Privacy Enhancing Technologies Symposium",
    "PRL",
    "PRL Pattern Recognition Letters",
    "Proceedings of the ACM on Human-Computer Interaction",
    "PUC",
    "PUC Personal and Ubiquitous Computing",
    "QRS",
    "QRS International Conference on Software Quality, Reliability and Security",
    "Real-Time Systems",
    "REFSQ",
    "REFSQ Requirements Engineering: Foundation for Software Quality",
    "Requirements Engineering: Foundation for Software Quality",
    "RTS",
    "RTS Real-Time Systems",
    "RV",
    "RV International Conference on Runtime Verification",
    "SAC",
    "SAC Selected Areas in Cryptography",
    "SACMAT",
    "SACMAT ACM Symposium on Access Control Models and Technologies",
    "SAGT",
    "SAGT International Symposium on Algorithmic Game Theory",
    "SCAM",
    "SCAM IEEE International Working Conference on Source Code Analysis and Manipulation",
    "Science",
    "SCN",
    "SCN Security and Communication Networks",
    "SEC",
    "SEC ACM/IEEE Symposium on Edge Computing IEEE/",
    "SEC IFIP International Information Security Conference",
    "SecureComm",
    "SecureComm International Conference on Security and Privacy in Communication Networks",
    "Security and Communication Networks",
    "SEKE",
    "SEKE International Conference on Software Engineering and Knowledge Engineering KSI",
    "Selected Areas in Cryptography",
    "Service Oriented Computing and Applications",
    "Sets and Systems",
    "SIAM Journal on Discrete Mathematics",
    "SIDMA",
    "SIDMA SIAM Journal on Discrete Mathematics",
    "Signal Processing",
    "Signal Processing: Image Communication",
    "SIGPRO",
    "SIGPRO Signal Processing",
    "SIGSPATIAL",
    "SIGSPATIAL ACM Special Interest Group on Spatial Information",
    "SLT",
    "SLT Spoken Language Technology IEEE SLTC",
    "SMC",
    "SMC IEEE International Conference on Systems, Man, and Cybernetics",
    "SOCA",
    "SOCA Service Oriented Computing and Applications",
    "Soft",
    "Soft Computing",
    "Software Quality Journal",
    "SOUPS",
    "SOUPS Symposium On Usable Privacy and Security",
    "Speech & Language",
    "SPIN",
    "SPIN International Symposium on Model Checking of Software",
    "SPL",
    "SPL IEEE Signal Processing Letters",
    "Spoken Language Technology IEEE SLTC",
    "SQJ",
    "SQJ Software Quality Journal",
    "SSDBM",
    "SSDBM International Conference on Scientific and Statistical Database Management",
    "SSE",
    "SSE IEEE International Conference on Software Services Engineering",
    "SSTD",
    "SSTD International Symposium on Spatial and Temporal Databases",
    "STACS",
    "STACS Symposium on Theoretical Aspects of Computer Science",
    "STTT",
    "STTT International Journal of Software Tools for Technology Transfer",
    "Symposium on Theoretical Aspects of Computer Science",
    "Symposium On Usable Privacy and Security",
    "Systems Blackwell/",
    "SYSTOR",
    "SYSTOR ACM International Systems and Storage Conference",
    "TALLIP",
    "TALLIP ACM Transactions on Asian and Low-Resource Language Information Processing",
    "TASE",
    "TASE Theoretical Aspects of Software Engineering Conference",
    "TBD",
    "TBD IEEE Transactions on Big Data",
    "TCASI",
    "TCASI IEEE Transactions on Circuits and Systems I: Regular Papers",
    "TCPS",
    "TCPS ACM Transactions on Cyber-Physical Systems",
    "TELO",
    "TELO ACM Transactions on Evolutionary Learning and Optimization",
    "TG",
    "TG IEEE Transactions on Games",
    "The Cryptographer's Track at RSA Conference",
    "The International Conference on Wireless Artificial Intelligent Computing Systems and Applications",
    "The Journal of Strategic Information Systems",
    "The Journal of Supercomputing",
    "The Journal of Symbolic Logic Association for Symbolic Logic",
    "The Visual Computer",
    "Theoretical Aspects of Software Engineering Conference",
    "Theory",
    "Theory and Practice of Logic Programming",
    "Theory of Computing Systems",
    "THPC CCF Transactions on High Performance Computing CCF",
    "THRI",
    "THRI ACM Transactions on Human-Robot Interaction",
    "TII",
    "TII IEEE Transactions on Industrial Informatics",
    "TIIS",
    "TIIS ACM Transactions on Interactive Intelligent Systems",
    "TIOT",
    "TIOT ACM Transactions on Internet of Things",
    "TIST",
    "TIST ACM Transactions on Intelligent Systems and Technology",
    "TJSC",
    "TJSC The Journal of Supercomputing",
    "TNSM",
    "TNSM IEEE Transactions on Network and Service Management",
    "TOCE",
    "TOCE ACM Transactions on Computing Education",
    "TORS",
    "TORS ACM Transactions on Recommender Systems",
    "TPLP",
    "TPLP Theory and Practice of Logic Programming",
    "TQC",
    "TQC ACM Transactions in Quantum Computing",
    "Transactions on Reliability",
    "Translation",
    "TrustCom",
    "TrustCom IEEE International Conference on Trust, Security and Privacy in Computing and Communications",
    "TSUSC",
    "TSUSC IEEE Transactions on Sustainable Computing",
    "TVC",
    "TVC The Visual Computer",
    "TY Journal of Complexity",
    "UIC",
    "UIC IEEE International Conference on Ubiquitous Intelligence and Computing",
    "USENIX Workshop on Hot Topics in Security",
    "VI",
    "VI Visual Informatics 浙江大学出 版社",
    "Virtual Reality & Intelligent Hardware 中国科技出 版社/北京航 空航天大学",
    "Vision and Applications",
    "Visual Informatics 浙江大学出 版社",
    "VRIH",
    "VRIH Virtual Reality & Intelligent Hardware 中国科技出 版社/北京航 空航天大学",
    "VRST",
    "VRST ACM Symposium on Virtual Reality Software and Technology",
    "VTS",
    "VTS IEEE VLSI Test Symposium",
    "WAIM",
    "WAIM International Conference on Web Age Information Management",
    "WASA",
    "WASA The International Conference on Wireless Artificial Intelligent Computing Systems and Applications",
    "WCMC",
    "WCMC Wireless Communications and Mobile Computing",
    "WCNC",
    "WCNC IEEE Wireless Communications and Networking Conference",
    "Web Information Systems and Applications",
    "Web Intelligence",
    "WebDB",
    "WebDB International Workshop on Web and Databases",
    "WG 11.9 IFIP Working Group 11.9 International Conference on Digital Forensics",
    "WI",
    "WI Web Intelligence",
    "WICSA",
    "WICSA Working IEEE/IFIP Conference on Software Architecture",
    "Wireless",
    "Wireless Communications and Mobile Computing",
    "Wireless Networks",
    "WISA",
    "WISA Web Information Systems and Applications",
    "WiSec",
    "WiSec ACM Conference on Security and Privacy in Wireless and Mobile Networks",
    "Working IEEE/IFIP Conference on Software Architecture",
    "World Haptics Conference",
    "WoWMoM",
    "WoWMoM IEEE International Symposium on a World of Wireless, Mobile and Multimedia Networks",
    "（原 IR） Discover Computing 5 IJCIS International Journal of Cooperative Information Systems",
  ],
};
